<?php

/**
 * Implements hook_region_plugins().
 */
function region_storage_database_region_plugins() {
  $path = drupal_get_path('module', 'region_storage_database') . '/plugins/region_storage';
  $info['region_storage_database'] = array(
    'title' => 'Database storage',
    'region_storage' => array(
      'parent' => 'RegionStorage',
      'class' => 'RegionStorageDatabase',
      'file' => 'region_storage_database.inc',
      'path' => $path,
    ),
  );
  return $info;
}
