entity_collection.collection.*:
  type: config_entity
  label: 'Entity Collection'
  mapping:
    uuid:
      type: string
    id:
      type: string
    label:
      type: label
      label: 'Name'
    admin_ui:
      type: string
      label: 'Admin UI'
    admin_ui_settings:
      type: entity_collection.collection.admin_ui.[%parent.admin_ui]
      label: 'Admin UI Settings'
    storage:
      type: string
      label: 'Storage plugin'
    storage_settings:
      type: entity_collection.collection.storage.[%parent.storage]
      label: 'Storage Settings'
    list_style:
      type: string
      label: 'List Style'
    list_style_settings:
      type: entity_collection.collection.list_style.[%parent.list_style]
      label: 'List plugin settings'
    row_display:
      type: string
      label: 'Row Display'
    row_display_settings:
      type: entity_collection.collection.row_display.[%parent.row_display]
      label: 'Row plugin settings'

entity_collection.collection.admin_ui.table_form:
  type: mapping
  label: 'Table Form configuration'
  mapping: {}

entity_collection.collection.list_style.flat_list:
  type: mapping
  label: 'Flat List style configuration'
  mapping: {}


entity_collection.collection.row_display.view_mode:
  type: mapping
  label: 'View mode row configuration'
  mapping:
    configurable:
      type: boolean
      label: 'View mode per each Row'
